version: '3.8'

services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db
    networks:
      - reactive-net
  db:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INITDB_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"
    networks:
      - reactive-net
  box:
    image: busybox
    volumes:
      - /box
    networks:
      - reactive-net
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"
    networks:
      - reactive-net
networks:
  reactive-net:
    name: custom-net
volumes:
  db:
  box: